# Generated by Django 3.0.4 on 2020-03-29 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centromedico',
            name='medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.Medico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centromedico',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='historiaClinica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.HistoriaClinica'),
            preserve_default=False,
        ),
    ]
