# Generated by Django 3.0.6 on 2020-06-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0002_auto_20200329_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='Evento',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='Especialidad',
            new_name='cedula',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
